#!/bin/sh

# Get the desired version from user
while true; do
    read -p "Please choose python version you want to install (2.7, 3.3, 3.5, etc.)? " version
    case $version in
    	 [0-9].[0-9][.]*[0-9]*) echo $version; break;;

	 * ) echo "Default version is 2.7.11"; version=2.7.11; break;;
    esac
done

# Install dependencies
sudo apt-get install build-essential checkinstall
sudo apt-get install libreadline-gplv2-dev libncursesw5-dev libssl-dev libsqlite3-dev tk-dev libgdbm-dev libc6-dev libbz2-dev

mkdir -p ~/Downloads/ # Create Downloads directory if it does not exist 
cd ~/Downloads/
wget "http://python.org/ftp/python/$version/Python-$version.tgz"
tar -xvf "Python-$version.tgz"
cd "Python-$version"

./configure
make
sudo checkinstall

# Install pip
cd ~/Downloads/
curl "https://bootstrap.pypa.io/get-pip.py" -o "get-pip.py"
sudo python get-pip.py

# Install django
pip install Django=1.7.4
